# Generated by Django 4.2.2 on 2023-09-26 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_blog_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
